# Generated by Django 5.2.11 on 2026-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusage',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Ilova nazorati', 'verbose_name_plural': 'Ilova nazoratlari'},
        ),
        migrations.AlterModelOptions(
            name='familyrelation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='appusage',
            name='usage_time',
            field=models.IntegerField(default=0, verbose_name='Foydalanish vaqti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='familyrelation',
            name='child_label',
            field=models.CharField(help_text='Masalan: O‘g‘lim Ali', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='appusage',
            constraint=models.UniqueConstraint(fields=('user', 'app_name'), name='unique_user_app_usage'),
        ),
    ]
