# Generated by Django 5.2.11 on 2026-03-11 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ilova nazorati', 'verbose_name_plural': 'Ilova nazoratlari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Geolokatsiya', 'verbose_name_plural': 'Geolokatsiyalar'},
        ),
        migrations.AlterField(
            model_name='appusage',
            name='app_name',
            field=models.CharField(max_length=255, verbose_name='Ilova nomi'),
        ),
        migrations.AlterField(
            model_name='appusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='appusage',
            name='usage_time',
            field=models.IntegerField(verbose_name='Foydalanish vaqti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='appusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP kod'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lat',
            field=models.FloatField(verbose_name='Kenglik (lat)'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lng',
            field=models.FloatField(verbose_name='Uzunlik (lng)'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
