# Generated by Django 5.2.11 on 2026-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appusage_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Ota-ona'), ('child', 'Farzand')], default='parent', max_length=10, verbose_name='Rol'),
        ),
    ]
